"""Add flair to the data

Revision ID: 29a2a7e29b86
Revises: 042e0e5977cf
Create Date: 2020-07-25 17:19:41.634045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a2a7e29b86'
down_revision = '042e0e5977cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
